train_root: data/ocr_dataset_train_400_10/
test_root: data/ocr_dataset_train_50_10_val/
batch_size: 20
max_len: 15
img_h: 32
img_w: 150
n_hidden: 512
n_iter: 400
lr: 0.00005
cuda: True
val_interval: 250
save_interval: 1000
model_dir: models
debug_level: 20
experiment: experiment
n_channel: 3
n_class: 11
beta: 0.5
